//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GimaSoft.Business.GINA.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.13.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DataFolder {
            get {
                return ((string)(this["DataFolder"]));
            }
            set {
                this["DataFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".")]
        public string MediaFolder {
            get {
                return ((string)(this["MediaFolder"]));
            }
            set {
                this["MediaFolder"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("eqgame.exe")]
        public string EverquestGameFile {
            get {
                return ((string)(this["EverquestGameFile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AudioTriggers")]
        public string EverquestAudioTriggersFolder {
            get {
                return ((string)(this["EverquestAudioTriggersFolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("userdata")]
        public string EverquestUserDataFolder {
            get {
                return ((string)(this["EverquestUserDataFolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ui_(?\'char\'.+)_(?\'server\'\\w+)\\.ini")]
        public string EverquestUIFileRegex {
            get {
                return ((string)(this["EverquestUIFileRegex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AT_(?<triggerSet>\\w+)_(?<char>\\w+)_(?<server>\\w+)\\.ini")]
        public string EverquestATFileRegex {
            get {
                return ((string)(this["EverquestATFileRegex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AT_{0}_{1}_{2}.ini")]
        public string EverquestATFileFormat {
            get {
                return ((string)(this["EverquestATFileFormat"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ui_*_*.ini")]
        public string EverquestUIFileMask {
            get {
                return ((string)(this["EverquestUIFileMask"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AT_*_*_*.ini")]
        public string EverquestATFileMask {
            get {
                return ((string)(this["EverquestATFileMask"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Pattern(?<id>[0-9]*)=(?<pattern>[^\\r\\n]+)\\r\\nSound[0-9]*=(?<sound>[^\\r\\n]*)")]
        public string EverquestTriggerFileRegex {
            get {
                return ((string)(this["EverquestTriggerFileRegex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("^\\[\\w{3} (?\'month\'\\w{3}) (?\'date\'\\d{1,2}) (?\'hour\'\\d{1,2}):(?\'minute\'\\d{2}):(?\'se" +
            "cond\'\\d{2}) (?\'year\'\\d{4})\\]\\s(?\'text\'.+)$")]
        public string EverquestLogLineFormat {
            get {
                return ((string)(this["EverquestLogLineFormat"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("^\\[[^\\]]+\\] (?\'name\'\\w+).+\\{GINA:(?\'sessionid\'[^\\}]+)\\}")]
        public string EverquestShareFormat {
            get {
                return ((string)(this["EverquestShareFormat"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\{GINA:(?\'sessionid\'[^\\}]+)\\}")]
        public string DefaultShareFormat {
            get {
                return ((string)(this["DefaultShareFormat"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://eq.gimasoft.com/GINAServices/Package.svc")]
        public string DefaultShareServiceUri {
            get {
                return ((string)(this["DefaultShareServiceUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Logs")]
        public string EverquestLogFolder {
            get {
                return ((string)(this["EverquestLogFolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("gin")]
        public string EverquestMetadataExtension {
            get {
                return ((string)(this["EverquestMetadataExtension"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("gtp")]
        public string GINAPackageFileExtension {
            get {
                return ((string)(this["GINAPackageFileExtension"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("gtt")]
        public string GamTextTriggerExtension {
            get {
                return ((string)(this["GamTextTriggerExtension"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Trigger=(?<TriggerText>.+);Comment=(?<Comments>.+);Display=.+;ShowText=(?<UseText>.+);DisplayText=(?<DisplayText>.+);ShowLine=(?<ShowLine>.+);TextColour=(?<OverlayColor>.+);Timer=(?<UseTimer>.+);TimerText=(?<TimerText>.+);Hours=(?<TimerHours>.+);Minutes=(?<TimerMinutes>.+);Seconds=(?<TimerSeconds>.+);Behaviour=(?<TimerBehavior>.+);CompletionDisplay=(?<UseTimerCompleteText>.+);CompletionText=(?<TimerCompleteText>.+);EndEarly=(?<UseTimerEndEarlyText>.+);EndEarlyText=(?<TimerEndEarlyText>.+);Sound=(?<UseSound>.+);PlaySound=(?<PlayMediaFile>.+);SoundLink=(?<MediaFileName>.+);PlayTTS=(?<UseTextToVoice>.+);TTSText=(?<TextToVoiceText>.+);")]
        public string GamTextTriggerImportRegex {
            get {
                return ((string)(this["GamTextTriggerImportRegex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Trigger={TriggerText};Comment={Comments};Display={UseText};ShowText={ShowText};DisplayText={DisplayText};ShowLine={ShowLine};TextColour={OverlayColor};Timer={UseTimer};TimerText={TimerText};Hours={TimerHours};Minutes={TimerMinutes};Seconds={TimerSeconds};Behaviour={TimerBehavior};CompletionDisplay={UseTimerCompleteText};CompletionText={TimerCompleteText};EndEarly={UseTimerEndEarlyText};EndEarlyText={TimerEndEarlyText};Sound={UseSound};PlaySound={PlayMediaFile};SoundLink={MediaFileName};PlayTTS={UseTextToVoice};TTSText={TextToVoiceText};")]
        public string GamTextTriggerExportFormat {
            get {
                return ((string)(this["GamTextTriggerExportFormat"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GTT:{0}")]
        public string GamTextTriggerClipboardFormat {
            get {
                return ((string)(this["GamTextTriggerClipboardFormat"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GTT:Trigger=")]
        public string GamTextTriggerFastMatch {
            get {
                return ((string)(this["GamTextTriggerFastMatch"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("^(?\'name\'\\w+).+GTT:Trigger=")]
        public string GamTextTriggerShareRegex {
            get {
                return ((string)(this["GamTextTriggerShareRegex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("lkg")]
        public string LastKnownGoodExtension {
            get {
                return ((string)(this["LastKnownGoodExtension"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("bad")]
        public string BadFileExtension {
            get {
                return ((string)(this["BadFileExtension"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://eq.gimasoft.com/gina/changelog.aspx")]
        public string GINAChangeLogURL {
            get {
                return ((string)(this["GINAChangeLogURL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("^((You)|({C})) .*\\{GINA:(?\'cmd\'[^\\}]+)\\}")]
        public string EverquestGINACommandFormat {
            get {
                return ((string)(this["EverquestGINACommandFormat"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("27")]
        public int EverquestFastSearchSkip {
            get {
                return ((int)(this["EverquestFastSearchSkip"]));
            }
        }
    }
}
